language: ruby
cache: bundler
sudo: false
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - jruby-9.0.5.0
  - rbx-2
gemfile:
  - Gemfile
  - gemfiles/Gemfile-4-0-stable
  - gemfiles/Gemfile-4-1-stable
  - gemfiles/Gemfile-4-2-stable
  - gemfiles/Gemfile-5-0-stable
matrix:
  exclude:
    - gemfile: Gemfile
    - gemfile: gemfiles/Gemfile-5-0-stable
  include:
    - gemfile: Gemfile
      rvm: 2.2.5
    - gemfile: Gemfile
      rvm: 2.3.1
    - gemfile: gemfiles/Gemfile-5-0-stable
      rvm: 2.2.5
    - gemfile: gemfiles/Gemfile-5-0-stable
      rvm: 2.3.1
notifications:
  email: false
  campfire:
    secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
