language: ruby
cache: bundler
# To use rbx environment.
dist: trusty
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.2.6.0
  - rbx-3
gemfile:
  - Gemfile
  - gemfiles/Gemfile-5-2-stable
matrix:
  exclude:
    - gemfile: Gemfile
  include:
    - gemfile: Gemfile
      rvm: 2.5
    - gemfile: Gemfile
      rvm: 2.6
    - gemfile: Gemfile
      rvm: ruby-head
    - gemfile: Gemfile
      rvm: rbx-3
    - gemfile: gemfiles/Gemfile-5-2-stable
      rvm: 2.2
    - gemfile: gemfiles/Gemfile-5-2-stable
      rvm: 2.3
    - gemfile: gemfiles/Gemfile-5-2-stable
      rvm: 2.4
    - gemfile: gemfiles/Gemfile-5-2-stable
      rvm: 2.5
    - gemfile: gemfiles/Gemfile-5-2-stable
      rvm: 2.6
    - gemfile: gemfiles/Gemfile-5-2-stable
      rvm: ruby-head
    - gemfile: gemfiles/Gemfile-5-2-stable
      rvm: rbx-3
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
notifications:
  email: false
  campfire:
    secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
